In [159]:
import numpy as np

In [160]:
-(0.85)*np.log2(0.85)+(-(0.15)*np.log2(0.15)) # base entropy

0.6098403047164004

In [161]:
n = 3333

In [162]:
no_churn = 2850
churn = (n-no_churn)

In [163]:
no_churn/n

0.8550855085508551

In [164]:
churn/n

0.14491449144914492

In [165]:
# after split weighted entropy


In [166]:
2664/3010

0.8850498338870432

In [167]:
# if int. plan = Yes
(-(0.57)*np.log2(0.57)+(-(0.43)*np.log2(0.43))*(323/3333))

0.5129891762684786

In [168]:
# if int. plan = No
(-(0.88)*np.log2(0.88)+(-(0.12)*np.log2(0.12))*(3010/3333))

0.4937884922337441

In [169]:
# Entropy after split
(-(0.57)*np.log2(0.57)+(-(0.43)*np.log2(0.43))*(323/3333))+(-(0.88)*np.log2(0.88)+(-(0.12)*np.log2(0.12))*(3010/3333))

1.0067776685022227

In [170]:
-(0.5)*np.log2(0.5)+(-(0.5)*np.log2(0.5)) # base entropy

1.0

In [171]:
# Import the dataset

In [172]:
import pandas as pd
df_total = pd.read_csv('C:/Users/Administrator/Desktop/PM/Final_ChurnData.csv')

In [173]:
X = df_total[['account_length', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'area_code_tr']]
Y = df_total['target_churn_dum']

In [174]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [175]:
df_total.columns

Index(['Unnamed: 0', 'state', 'account_length', 'number_vmail_messages',
       'total_day_minutes', 'total_day_calls', 'total_day_charge',
       'total_eve_minutes', 'total_eve_calls', 'total_eve_charge',
       'total_night_minutes', 'total_night_calls', 'total_night_charge',
       'total_intl_minutes', 'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'area_code_tr', 'target_churn_dum'],
      dtype='object')

In [176]:
del df_total['Unnamed: 0']

In [177]:
del df_total['state']

In [178]:
Y = np.array(df_total.pop('target_churn_dum'))
X = np.array(df_total)

In [243]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size=0.20,random_state=5555)

In [244]:
xtrain.shape,xtest.shape,ytrain.shape,ytest.shape

((2666, 16), (667, 16), (2666,), (667,))

In [245]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, pydotplus
from sklearn import tree, metrics, model_selection, preprocessing
from IPython.display import Image, display

In [246]:
!pip install pydotplus

You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [247]:
dt1 = tree.DecisionTreeClassifier()

In [248]:
dt1

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [249]:
help(dt1)

Help on DecisionTreeClassifier in module sklearn.tree.tree object:

class DecisionTreeClassifier(BaseDecisionTree, sklearn.base.ClassifierMixin)
 |  A decision tree classifier.
 |  
 |  Read more in the :ref:`User Guide <tree>`.
 |  
 |  Parameters
 |  ----------
 |  criterion : string, optional (default="gini")
 |      The function to measure the quality of a split. Supported criteria are
 |      "gini" for the Gini impurity and "entropy" for the information gain.
 |  
 |  splitter : string, optional (default="best")
 |      The strategy used to choose the split at each node. Supported
 |      strategies are "best" to choose the best split and "random" to choose
 |      the best random split.
 |  
 |  max_depth : int or None, optional (default=None)
 |      The maximum depth of the tree. If None, then nodes are expanded until
 |      all leaves are pure or until all leaves contain less than
 |      min_samples_split samples.
 |  
 |  min_samples_split : int, float, optional (default=2

In [250]:
dt1.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [251]:
dt1.score(xtrain,ytrain)

1.0

In [252]:
dt1.score(xtest,ytest)

0.848575712143928

In [253]:
dt2 = tree.DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=30,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [254]:
dt2.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=30,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [255]:
dt2.score(xtrain,ytrain)

0.917854463615904

In [256]:
dt2.score(xtest,ytest)

0.9010494752623688

In [257]:
pred_y = dt2.predict(xtest)

In [258]:
confusion_matrix(pred_y,ytest)

array([[539,  45],
       [ 21,  62]], dtype=int64)

In [259]:
print(classification_report(pred_y,ytest))

              precision    recall  f1-score   support

           0       0.96      0.92      0.94       584
           1       0.58      0.75      0.65        83

    accuracy                           0.90       667
   macro avg       0.77      0.83      0.80       667
weighted avg       0.91      0.90      0.91       667



In [260]:
pd.Series(ytrain).value_counts()/ytrain.shape[0]

0    0.858965
1    0.141035
dtype: float64

In [261]:
pd.Series(ytest).value_counts()/ytest.shape[0]

0    0.83958
1    0.16042
dtype: float64

In [262]:
df_total.columns

Index(['account_length', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'area_code_tr'],
      dtype='object')

In [263]:
ytrain

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [264]:
!pip install GraphViz

You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [265]:
import numpy as np, pandas as pd, matplotlib.pyplot as plt, pydotplus
from sklearn import tree, metrics, model_selection, preprocessing
from IPython.display import Image, display

In [266]:
dt2

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=30,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [267]:
dt2.feature_importances_

array([0.        , 0.05644811, 0.23001087, 0.        , 0.2214436 ,
       0.13532337, 0.        , 0.04215073, 0.02128279, 0.        ,
       0.        , 0.03430824, 0.        , 0.        , 0.25903229,
       0.        ])

In [268]:
temp = ['account_length', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'area_code_tr']

In [269]:
#1.# mean decrease in gini coefficient
#2.# max drop in entorpy
#3.# highest misclassification error rate

dot_data = tree.export_graphviz(dt2, 
                                out_file=None, 
                                filled=True, 
                                rounded=True,
                                feature_names=['account_length', 'number_vmail_messages', 'total_day_minutes',
       'total_day_calls', 'total_day_charge', 'total_eve_minutes',
       'total_eve_calls', 'total_eve_charge', 'total_night_minutes',
       'total_night_calls', 'total_night_charge', 'total_intl_minutes',
       'total_intl_calls', 'total_intl_charge',
       'number_customer_service_calls', 'area_code_tr'],  
                                class_names=['0', '1'])
graph = pydotplus.graph_from_dot_data(dot_data)  
display(Image(graph.create_png()))

In [270]:
# hyper parameter tuning or selection of best parameters which can balance the trade off between bias and variance in a model

In [271]:
dt2.score(xtrain,ytrain)

0.917854463615904

In [272]:
dt2.score(xtest,ytest)

0.9010494752623688

In [273]:
dt2

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=10, min_samples_split=30,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [274]:
# training :- 0.9186046511627907
# test: - 0.9265367316341829

In [275]:
# training:- 0.9147021003000428
# test: - 0.91

In [ ]:
# training: 0.917854463615904
# test:- 0.90

In [276]:
from sklearn.model_selection import KFold

In [277]:
from sklearn.model_selection import cross_val_score

In [278]:
scores = cross_val_score(estimator= dt2,     # Model to test
                X= xtrain,  
                y = ytrain,      # Target variable
                scoring = "accuracy",               # Scoring metric    
                cv=10)                              # Cross validation folds

print("Accuracy per fold: ")
print(scores)
print("Average accuracy: ", scores.mean())
print('Deviation: ', scores.std())

Accuracy per fold: 
[0.92134831 0.90636704 0.88014981 0.89138577 0.89513109 0.92509363
 0.90601504 0.91353383 0.89849624 0.90225564]
Average accuracy:  0.9039776407310411
Deviation:  0.012986145373196796


In [279]:
scores = cross_val_score(estimator= dt1,     # Model to test
                X= xtrain,  
                y = ytrain,      # Target variable
                scoring = "accuracy",               # Scoring metric    
                cv=10)                              # Cross validation folds

print("Accuracy per fold: ")
print(scores)
print("Average accuracy: ", scores.mean())
print('Deviation: ', scores.std())

Accuracy per fold: 
[0.88014981 0.87265918 0.83146067 0.88389513 0.84644195 0.87265918
 0.84210526 0.89473684 0.85714286 0.85338346]
Average accuracy:  0.8634634338655627
Deviation:  0.01937698008771965


In [280]:
# selection of hyper parameters through grid search

In [281]:
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import GridSearchCV

In [282]:
# create a function to perform grid search with cross validation and returns the accuracy values
def GridSearch_BestParam(X, y, clf, param_grid,cv=10):
    grid_search = GridSearchCV(clf,
                              param_grid=param_grid,
                              cv=cv)
    start= time()
    grid_search.fit(X,y)
    top_params=grid_search.best_params_
    return top_params

In [283]:
from sklearn.model_selection import GridSearchCV
from time import time
from operator import itemgetter

In [286]:
param_grid = {"criterion": ["gini","entropy"],
             "max_depth": [2,3,5,7,10,12,15],
              "min_samples_split":[10,15,20,30]
             }

In [287]:
#help(dt2)

In [289]:
2*7*4*10

560

In [291]:
clf = tree.DecisionTreeClassifier() 

In [292]:
clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [293]:
top_para = GridSearch_BestParam(xtrain,ytrain, clf, param_grid, cv=10)
print (top_para)

{'criterion': 'entropy', 'max_depth': 7, 'min_samples_split': 15}


In [295]:
best_dtmodel = tree.DecisionTreeClassifier(max_depth=7, 
                                           min_samples_split=15,
                                   criterion='entropy')
best_dtmodel

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=15,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [296]:
best_dtmodel.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=15,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [299]:
np.round(best_dtmodel.score(xtrain,ytrain),2)

0.94

In [300]:
np.round(best_dtmodel.score(xtest,ytest),2)

0.9

In [305]:
best_dtmodel.feature_importances_[np.round(best_dtmodel.feature_importances_,1) > 0]

array([0.06563897, 0.33361785, 0.10271559, 0.07857355, 0.1790634 ])

In [307]:
# Multiclass Decision Tree for Classification

In [308]:
import pandas as pd

In [378]:
red_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',
                      sep=';')

In [379]:
white_wine = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv',
                        sep=';')

In [380]:
red_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [381]:
white_wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [382]:
wine = pd.concat([red_wine,white_wine])

In [383]:
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [384]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6497 entries, 0 to 4897
Data columns (total 12 columns):
fixed acidity           6497 non-null float64
volatile acidity        6497 non-null float64
citric acid             6497 non-null float64
residual sugar          6497 non-null float64
chlorides               6497 non-null float64
free sulfur dioxide     6497 non-null float64
total sulfur dioxide    6497 non-null float64
density                 6497 non-null float64
pH                      6497 non-null float64
sulphates               6497 non-null float64
alcohol                 6497 non-null float64
quality                 6497 non-null int64
dtypes: float64(11), int64(1)
memory usage: 659.9 KB


Citation Request:
  This dataset is public available for research. The details are described in [Cortez et al., 2009]. 
  Please include this citation if you plan to use this database:

  P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis. 
  Modeling wine preferences by data mining from physicochemical properties.
  In Decision Support Systems, Elsevier, 47(4):547-553. ISSN: 0167-9236.

  Available at: [@Elsevier] http://dx.doi.org/10.1016/j.dss.2009.05.016
                [Pre-press (pdf)] http://www3.dsi.uminho.pt/pcortez/winequality09.pdf
                [bib] http://www3.dsi.uminho.pt/pcortez/dss09.bib

1. Title: Wine Quality 

2. Sources
   Created by: Paulo Cortez (Univ. Minho), Antonio Cerdeira, Fernando Almeida, Telmo Matos and Jose Reis (CVRVV) @ 2009
   
3. Past Usage:

  P. Cortez, A. Cerdeira, F. Almeida, T. Matos and J. Reis. 
  Modeling wine preferences by data mining from physicochemical properties.
  In Decision Support Systems, Elsevier, 47(4):547-553. ISSN: 0167-9236.

  In the above reference, two datasets were created, using red and white wine samples.
  The inputs include objective tests (e.g. PH values) and the output is based on sensory data
  (median of at least 3 evaluations made by wine experts). Each expert graded the wine quality 
  between 0 (very bad) and 10 (very excellent). Several data mining methods were applied to model
  these datasets under a regression approach. The support vector machine model achieved the
  best results. Several metrics were computed: MAD, confusion matrix for a fixed error tolerance (T),
  etc. Also, we plot the relative importances of the input variables (as measured by a sensitivity
  analysis procedure).
 
4. Relevant Information:

   The two datasets are related to red and white variants of the Portuguese "Vinho Verde" wine.
   For more details, consult: http://www.vinhoverde.pt/en/ or the reference [Cortez et al., 2009].
   Due to privacy and logistic issues, only physicochemical (inputs) and sensory (the output) variables 
   are available (e.g. there is no data about grape types, wine brand, wine selling price, etc.).

   These datasets can be viewed as classification or regression tasks.
   The classes are ordered and not balanced (e.g. there are munch more normal wines than
   excellent or poor ones). Outlier detection algorithms could be used to detect the few excellent
   or poor wines. Also, we are not sure if all input variables are relevant. So
   it could be interesting to test feature selection methods. 

5. Number of Instances: red wine - 1599; white wine - 4898. 

6. Number of Attributes: 11 + output attribute
  
   Note: several of the attributes may be correlated, thus it makes sense to apply some sort of
   feature selection.

7. Attribute information:

   For more information, read [Cortez et al., 2009].

   Input variables (based on physicochemical tests):
   1 - fixed acidity
   2 - volatile acidity
   3 - citric acid
   4 - residual sugar
   5 - chlorides
   6 - free sulfur dioxide
   7 - total sulfur dioxide
   8 - density
   9 - pH
   10 - sulphates
   11 - alcohol
   Output variable (based on sensory data): 
   12 - quality (score between 0 and 10)

8. Missing Attribute Values: None


In [385]:
set(wine.quality)

{3, 4, 5, 6, 7, 8, 9}

In [386]:
wine.quality.value_counts()/wine.shape[0]

6    0.436509
5    0.329075
7    0.166077
4    0.033246
8    0.029706
3    0.004618
9    0.000770
Name: quality, dtype: float64

In [387]:
wine.quality.value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

In [388]:
wine.quality.replace({3:4,9:8},inplace=True)

In [389]:
wine.quality.value_counts()

6    2836
5    2138
7    1079
4     246
8     198
Name: quality, dtype: int64

In [390]:
wine.quality.replace({8:7,4:5},inplace=True)

In [391]:
wine.quality = pd.Categorical(wine.quality)

In [392]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6497 entries, 0 to 4897
Data columns (total 12 columns):
fixed acidity           6497 non-null float64
volatile acidity        6497 non-null float64
citric acid             6497 non-null float64
residual sugar          6497 non-null float64
chlorides               6497 non-null float64
free sulfur dioxide     6497 non-null float64
total sulfur dioxide    6497 non-null float64
density                 6497 non-null float64
pH                      6497 non-null float64
sulphates               6497 non-null float64
alcohol                 6497 non-null float64
quality                 6497 non-null category
dtypes: category(1), float64(11)
memory usage: 615.5 KB


In [393]:
Y = wine.pop('quality')
X = wine

In [394]:
xtrain, xtest, ytrain, ytest = train_test_split(X,Y, test_size= 0.20,random_state=1234)

In [395]:
xtrain.shape, ytrain.shape, xtest.shape, ytest.shape

((5197, 11), (5197,), (1300, 11), (1300,))

In [396]:
clf

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [397]:
top_para = GridSearch_BestParam(xtrain,ytrain, clf, param_grid, cv=10)
print (top_para)

{'criterion': 'gini', 'max_depth': 12, 'min_samples_split': 10}


In [398]:
best_dtmodel = tree.DecisionTreeClassifier(criterion= 'gini', max_depth= 12, min_samples_split=10)

In [399]:
best_dtmodel.fit(xtrain,ytrain)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=12,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=10,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [400]:
best_dtmodel.score(xtrain,ytrain)
# 0.84298633827208

0.823744467962286

In [402]:
best_dtmodel.score(xtest,ytest)
#0.5484615384615384

0.5953846153846154

In [403]:
pred_y = best_dtmodel.predict(xtest)

In [404]:
from sklearn.metrics import classification_report, confusion_matrix

In [405]:
confusion_matrix(ytest,pred_y)

array([[323, 118,  24],
       [163, 306,  95],
       [ 22, 104, 145]], dtype=int64)

In [406]:
print(classification_report(ytest,pred_y))

              precision    recall  f1-score   support

           5       0.64      0.69      0.66       465
           6       0.58      0.54      0.56       564
           7       0.55      0.54      0.54       271

    accuracy                           0.60      1300
   macro avg       0.59      0.59      0.59      1300
weighted avg       0.59      0.60      0.59      1300



In [409]:
pred_y[0:10]

array([7, 5, 6, 6, 5, 6, 6, 7, 5, 7], dtype=int64)

In [408]:
pd.DataFrame(best_dtmodel.predict_proba(xtest))

0         1         2
0     0.000000  0.000000  1.000000
1     1.000000  0.000000  0.000000
2     0.125000  0.500000  0.375000
3     0.428571  0.571429  0.000000
4     0.461538  0.461538  0.076923
5     0.000000  1.000000  0.000000
6     0.192308  0.807692  0.000000
7     0.000000  0.000000  1.000000
8     0.807692  0.192308  0.000000
9     0.000000  0.000000  1.000000
10    1.000000  0.000000  0.000000
11    0.027523  0.238532  0.733945
12    0.829545  0.170455  0.000000
13    0.333333  0.000000  0.666667
14    0.027523  0.238532  0.733945
15    1.000000  0.000000  0.000000
16    0.181102  0.535433  0.283465
17    0.000000  1.000000  0.000000
18    1.000000  0.000000  0.000000
19    0.000000  0.000000  1.000000
20    0.250000  0.000000  0.750000
21    0.000000  0.956522  0.043478
22    0.000000  1.000000  0.000000
23    0.000000  0.900000  0.100000
24    0.166667  0.500000  0.333333
25    0.041379  0.262069  0.696552
26    0.664975  0.329949  0.005076
27    0.041379  0.262069  0.696552
28    0.000000  1.000000  0.000000
29    0.000000  1.000000  0.000000
...        ...       ...       ...
1270  0.807692  0.192308  0.000000
1271  0.000000  1.000000  0.000000
1272  0.000000  1.000000  0.000000
1273  0.676056  0.309859  0.014085
1274  0.921053  0.078947  0.000000
1275  0.000000  1.000000  0.000000
1276  0.000000  1.000000  0.000000
1277  0.526316  0.473684  0.000000
1278  1.000000  0.000000  0.000000
1279  0.222222  0.333333  0.444444
1280  0.071429  0.928571  0.000000
1281  0.829545  0.170455  0.000000
1282  0.000000  1.000000  0.000000
1283  1.000000  0.000000  0.000000
1284  1.000000  0.000000  0.000000
1285  0.000000  1.000000  0.000000
1286  0.829545  0.170455  0.000000
1287  0.000000  1.000000  0.000000
1288  0.664975  0.329949  0.005076
1289  0.333333  0.333333  0.333333
1290  1.000000  0.000000  0.000000
1291  0.807692  0.192308  0.000000
1292  1.000000  0.000000  0.000000
1293  0.664975  0.329949  0.005076
1294  0.000000  0.000000  1.000000
1295  0.166667  0.500000  0.333333
1296  0.333333  0.666667  0.000000
1297  0.269231  0.692308  0.038462
1298  0.259259  0.703704  0.037037
1299  0.000000  1.000000  0.000000

[1300 rows x 3 columns]

In [411]:
# Assignment:
# create bins for all the features in this wine quality dataset
# the bins should be in H, M and L, three classes based on the probability value
# retrain the model using grid search approach
# report the accuracy F-score and classification report